spring:
  datasource:
    url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/habit-service}
    username: ${POSTGRES_DATABASE_USERNAME:habit-service}
    password: ${POSTGRES_DATABASE_PASSWORD:habit-service}